name: Test native launchers
on:
  push:
    branches:
    - main
  pull_request:

jobs:

  test-native-launchers:
    strategy:
      fail-fast: false
      matrix:
        OS: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3.0
        with:
          jvm: 8
      - run: sudo apt-get install -y nailgun
        if: runner.os == 'Linux'
      - run: .github/scripts/maybe-with-graalvm-home.sh nativeTests
        shell: bash
      - name: Copy artifacts
        run: .github/scripts/maybe-with-graalvm-home.sh copyLauncher artifacts/
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2

  test-native-static-launcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3.0
        with:
          jvm: 8
      - run: sudo apt-get install -y nailgun
        if: runner.os == 'Linux'
      - run: .github/scripts/maybe-with-graalvm-home.sh nativeStaticTests
        shell: bash
      - name: Copy artifacts
        run: .github/scripts/maybe-with-graalvm-home.sh copyStaticLauncher artifacts/
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2

  test-native-mostly-static-launcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3.0
        with:
          jvm: 8
      - run: sudo apt-get install -y nailgun
        if: runner.os == 'Linux'
      - run: .github/scripts/maybe-with-graalvm-home.sh nativeMostlyStaticTests
        shell: bash
      - name: Copy artifacts
        run: .github/scripts/maybe-with-graalvm-home.sh copyMostlyStaticLauncher artifacts/
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2
